# Generated by Django 5.1.7 on 2025-05-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionbooking',
            old_name='summary_complaint',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='phone',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
