# Generated by Django 5.1.5 on 2025-05-06 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_summary_complaint_sessionbooking_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
